import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";

const body = localFont({
  src: "./fonts/THARWATEMARARUQAA.ttf",
  variable: "--font-Ruquaa",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Greek Mythology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="AR" dir="rtl">
      <body className={`${body.className} antialiased text-white bg-black`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
